/**
 * ClaimVerifyWorkflow Definition
 * Verify claims from content
 *
 * @generated by inquiry-cli
 */

import type {
  WorkflowDefinition,
  WorkflowStep,
  AgentStep,
  SequentialStep,
  ParallelStep,
  ConditionalStep,
  TransformStep,
  WaitStep,
  WorkflowParameter,
  WorkflowOutput,
  RetryConfig,
} from '../types/index.js';

/**
 * Input parameters for ClaimVerifyWorkflow.
 */
export interface ClaimVerifyInput {
  /** Input data for the workflow */
  data: unknown;
}

/**
 * Output from ClaimVerifyWorkflow.
 */
export interface ClaimVerifyOutput {
  /** Result of the workflow */
  result: unknown;
  /** Processing metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Default retry configuration for ClaimVerifyWorkflow.
 */
export const claimVerifyWorkflowRetryConfig: RetryConfig = {
  maxAttempts: 3,
  initialDelayMs: 1000,
  maxDelayMs: 30000,
  backoffMultiplier: 2,
};

/**
 * Input parameters definition for ClaimVerifyWorkflow.
 */
export const claimVerifyWorkflowParameters: WorkflowParameter[] = [
  {
    name: 'data',
    type: 'object',
    description: 'Input data',
    required: true,
  },
];

/**
 * Output definitions for ClaimVerifyWorkflow.
 */
export const claimVerifyWorkflowOutputs: WorkflowOutput[] = [
  { name: 'result', type: 'object', source: 'output.result', description: 'Workflow result' },
];

/**
 * All steps for ClaimVerifyWorkflow.
 */
export const claimVerifyWorkflowSteps: WorkflowStep[] = [
];

/**
 * ClaimVerifyWorkflow definition.
 */
export const claimVerifyWorkflowDefinition: WorkflowDefinition = {
  id: 'claim-verify',
  name: 'ClaimVerifyWorkflow',
  description: 'Verify claims from content',
  version: '1.0.0',
  status: 'active',
  triggers: [
    {
      type: 'api',
      config: { enabled: true },
    },
  ],
  parameters: claimVerifyWorkflowParameters,
  outputs: claimVerifyWorkflowOutputs,
  entryStepId: 'entry',
  steps: claimVerifyWorkflowSteps,
  retryConfig: claimVerifyWorkflowRetryConfig,
  timeoutMs: 300000, // 5 minutes
  requiredAgents: [
  ],
  tags: ['custom', 'generated'],
  createdAt: Date.now(),
  updatedAt: Date.now(),
  createdBy: 'inquiry-cli',
};
