/**
 * Tests for ClaimVerifyWorkflow.
 *
 * @generated by inquiry-cli
 */

import { describe, it, expect, beforeEach } from 'vitest';
import {
  claimVerifyWorkflowDefinition,
  claimVerifyWorkflowSteps,
  claimVerifyWorkflowParameters,
  type ClaimVerifyInput,
} from './claim-verify.workflow.js';
import { ClaimVerifyWorkflowExecutor, executeClaimVerify } from './claim-verify.executor.js';

describe('ClaimVerifyWorkflow', () => {
  describe('definition', () => {
    it('should have a valid workflow definition', () => {
      expect(claimVerifyWorkflowDefinition).toBeDefined();
      expect(claimVerifyWorkflowDefinition.id).toBe('claim-verify');
      expect(claimVerifyWorkflowDefinition.name).toBe('ClaimVerifyWorkflow');
      expect(claimVerifyWorkflowDefinition.version).toMatch(/^\d+\.\d+\.\d+$/);
      expect(claimVerifyWorkflowDefinition.status).toBe('active');
    });

    it('should have steps defined', () => {
      expect(claimVerifyWorkflowSteps).toBeDefined();
      expect(Array.isArray(claimVerifyWorkflowSteps)).toBe(true);
    });

    it('should have entry step defined', () => {
      expect(claimVerifyWorkflowDefinition.entryStepId).toBeDefined();
    });

    it('should have valid parameters', () => {
      expect(claimVerifyWorkflowParameters).toBeDefined();
      expect(Array.isArray(claimVerifyWorkflowParameters)).toBe(true);

      for (const param of claimVerifyWorkflowParameters) {
        expect(param.name).toBeDefined();
        expect(param.type).toBeDefined();
        expect(typeof param.required).toBe('boolean');
      }
    });

  });

  describe('executor', () => {
    let executor: ClaimVerifyWorkflowExecutor;

    beforeEach(() => {
      executor = new ClaimVerifyWorkflowExecutor();
    });

    it('should create an executor instance', () => {
      expect(executor).toBeInstanceOf(ClaimVerifyWorkflowExecutor);
    });

    it('should start workflow execution', async () => {
      const input: ClaimVerifyInput = {
        data: { test: 'value' },
      };

      const execution = await executor.start(input);

      expect(execution).toBeDefined();
      expect(execution.id).toBeDefined();
      expect(execution.status).toBe('pending');
      expect(execution.workflowId).toBe('claim-verify');
    });

    it('should execute workflow', async () => {
      const input: ClaimVerifyInput = {
        data: { test: 'value' },
      };

      await executor.start(input);
      const result = await executor.execute();

      expect(result).toBeDefined();
      expect(result.executionId).toBeDefined();
      expect(['completed', 'failed']).toContain(result.status);
      expect(result.durationMs).toBeGreaterThanOrEqual(0);
    });

    it('should track execution context', async () => {
      const input: ClaimVerifyInput = {
        data: { test: 'value' },
      };

      await executor.start(input);

      const context = executor.getContext();
      expect(context).toBeDefined();
      expect(context?.input).toEqual(input);
      expect(context?.system.workflowId).toBe('claim-verify');
    });
  });

  describe('execute function', () => {
    it('should execute workflow with convenience function', async () => {
      const input: ClaimVerifyInput = {
        data: { test: 'value' },
      };

      const result = await executeClaimVerify(input);

      expect(result).toBeDefined();
      expect(result.executionId).toBeDefined();
      expect(result.metrics).toBeDefined();
    });
  });
});
