/**
 * Claim Node Type
 * A claim to be verified
 *
 * @generated by inquiry-cli
 */

/**
 * Claim node properties.
 */
export interface ClaimProperties {
  /** Unique identifier (UUID) */
  id: string;
  /** Creation timestamp */
  createdAt: Date;
  /** Last update timestamp */
  updatedAt: Date;
}

/**
 * Claim node with Neo4j metadata.
 */
export interface ClaimNode {
  /** Internal Neo4j node ID */
  _id: number;
  /** Node labels */
  _labels: string[];
  /** Node properties */
  properties: ClaimProperties;
}

/**
 * Input for creating a new Claim.
 */
export interface CreateClaimInput {
}

/**
 * Input for updating an existing Claim.
 */
export interface UpdateClaimInput {
}

/**
 * Filter criteria for querying Claim nodes.
 */
export interface ClaimFilter {
  /** Filter by id */
  id?: string;
  /** Filter by createdAt */
  createdAt?: Date;
}

/**
 * Neo4j label for Claim nodes.
 */
export const claimLabel = 'Claim' as const;

/**
 * Property keys for Claim nodes.
 */
export const claimPropertyKeys = [
  'id',
  'createdAt',
  'updatedAt',
] as const;

/**
 * Required property keys for Claim nodes.
 */
export const claimRequiredKeys = [
  'id',
  'createdAt',
  'updatedAt',
] as const;

/**
 * Indexed property keys for Claim nodes.
 */
export const claimIndexedKeys = [
  'id',
  'createdAt',
] as const;
